include $(PWD)/../dependencies.mk

.PHONY: problem-1
problem-1: dependencies
	venv/bin/python problem-1.py

.PHONY: problem-3
problem-3: dependencies
	venv/bin/python problem-3.py

.PHONY: problem-4
problem-4: dependencies
	venv/bin/python problem-4.py

