.PHONY: dependencies
dependencies:
	python -m venv venv
	venv/bin/pip install -r requirements.txt

.PHONY: problem-1
problem-1: dependencies
	venv/bin/python problem-2.py

.PHONY: problem-5
problem-5: dependencies
	venv/bin/python problem-5.py
